// Kamal Apparel - Products Database
// Comprehensive luxury fashion products with detailed information

const PRODUCTS = [
  // Men's Casual Pants
  {
    id: 'mp001',
    name: 'Premium Cotton Chinos - Navy',
    category: 'Casual',
    gender: 'Men',
    price: 4500,
    oldPrice: 5500,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    colors: ['Navy', 'Khaki', 'Black', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Premium cotton chinos with a modern slim fit. Perfect for casual office wear or weekend outings. Made from breathable fabric with excellent color retention.',
    rating: 4.8,
    reviews: 124,
    stock: 45,
    sku: 'KF-MP001'
  },
  {
    id: 'mp002',
    name: 'Slim Fit Denim Jeans - Dark Blue',
    category: 'Casual',
    gender: 'Men',
    price: 5200,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=800',
    colors: ['Dark Blue', 'Light Blue', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Classic slim fit denim jeans crafted from premium stretch denim. Features reinforced stitching and a comfortable mid-rise waist.',
    rating: 4.9,
    reviews: 203,
    stock: 62,
    sku: 'KF-MP002'
  },
  {
    id: 'mp003',
    name: 'Linen Blend Casual Pants - Beige',
    category: 'Casual',
    gender: 'Men',
    price: 4800,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
    colors: ['Beige', 'White', 'Light Gray'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Breathable linen blend pants perfect for summer. Lightweight and comfortable with a relaxed fit that maintains a polished look.',
    rating: 4.6,
    reviews: 87,
    stock: 38,
    sku: 'KF-MP003'
  },
  {
    id: 'mp004',
    name: 'Cargo Pants - Olive Green',
    category: 'Casual',
    gender: 'Men',
    price: 5500,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1624378440070-7b44c0b0b2e5?w=800',
    colors: ['Olive', 'Black', 'Khaki'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Modern cargo pants with multiple pockets and a contemporary fit. Made from durable cotton twill with reinforced seams.',
    rating: 4.7,
    reviews: 156,
    stock: 51,
    sku: 'KF-MP004'
  },

  // Men's Formal Pants
  {
    id: 'mf001',
    name: 'Wool Blend Dress Pants - Charcoal',
    category: 'Formal',
    gender: 'Men',
    price: 6500,
    oldPrice: 7500,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1594938291221-94f18cbb5660?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
    colors: ['Charcoal', 'Navy', 'Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Premium wool blend dress pants with a tailored fit. Perfect for business meetings and formal occasions. Features flat front and side pockets.',
    rating: 4.9,
    reviews: 178,
    stock: 34,
    sku: 'KF-MF001'
  },
  {
    id: 'mf002',
    name: 'Classic Fit Trousers - Navy',
    category: 'Formal',
    gender: 'Men',
    price: 5800,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594938291221-94f18cbb5660?w=800',
    colors: ['Navy', 'Black', 'Gray'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Timeless classic fit trousers in premium fabric. Versatile enough for office wear or formal events. Features belt loops and pleated front.',
    rating: 4.8,
    reviews: 145,
    stock: 42,
    sku: 'KF-MF002'
  },
  {
    id: 'mf003',
    name: 'Slim Fit Formal Pants - Black',
    category: 'Formal',
    gender: 'Men',
    price: 6200,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
    colors: ['Black', 'Navy', 'Charcoal'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Modern slim fit formal pants with a sleek silhouette. Made from wrinkle-resistant fabric for all-day comfort and style.',
    rating: 4.7,
    reviews: 132,
    stock: 39,
    sku: 'KF-MF003'
  },

  // Men's Traditional Wear
  {
    id: 'mt001',
    name: 'Premium Khaddar Shalwar - Cream',
    category: 'Traditional',
    gender: 'Men',
    price: 3500,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1622519407650-3df9883f76e5?w=800',
    colors: ['Cream', 'White', 'Light Gray'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Traditional khaddar shalwar with authentic craftsmanship. Perfect for casual and semi-formal occasions. Comfortable and breathable.',
    rating: 4.6,
    reviews: 98,
    stock: 56,
    sku: 'KF-MT001'
  },
  {
    id: 'mt002',
    name: 'Embroidered Kurta Pajama Set - Navy',
    category: 'Traditional',
    gender: 'Men',
    price: 8500,
    oldPrice: 9500,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1622519407650-3df9883f76e5?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    colors: ['Navy', 'Maroon', 'Black'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Elegant embroidered kurta pajama set perfect for festive occasions. Features intricate threadwork and premium fabric quality.',
    rating: 4.9,
    reviews: 167,
    stock: 28,
    sku: 'KF-MT002'
  },
  {
    id: 'mt003',
    name: 'Cotton Shalwar Kameez - White',
    category: 'Traditional',
    gender: 'Men',
    price: 4200,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1622519407650-3df9883f76e5?w=800',
    colors: ['White', 'Cream', 'Sky Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Classic cotton shalwar kameez for everyday wear. Comfortable, breathable, and easy to maintain. Perfect for casual occasions.',
    rating: 4.7,
    reviews: 189,
    stock: 67,
    sku: 'KF-MT003'
  },

  // Women's Casual Pants
  {
    id: 'wp001',
    name: 'High-Waist Palazzo Pants - Black',
    category: 'Casual',
    gender: 'Women',
    price: 4200,
    oldPrice: 5000,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    colors: ['Black', 'Navy', 'Maroon', 'Olive'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Elegant high-waist palazzo pants with a flowing silhouette. Perfect for both casual and semi-formal occasions. Made from soft, breathable fabric.',
    rating: 4.8,
    reviews: 156,
    stock: 48,
    sku: 'KF-WP001'
  },
  {
    id: 'wp002',
    name: 'Cigarette Pants - Beige',
    category: 'Casual',
    gender: 'Women',
    price: 3800,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    colors: ['Beige', 'Black', 'White', 'Gray'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Sleek cigarette pants with a modern slim fit. Versatile piece that pairs well with both casual and dressy tops. Features side pockets.',
    rating: 4.6,
    reviews: 112,
    stock: 52,
    sku: 'KF-WP002'
  },
  {
    id: 'wp003',
    name: 'Wide Leg Trousers - Navy',
    category: 'Casual',
    gender: 'Women',
    price: 4500,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    colors: ['Navy', 'Black', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Comfortable wide leg trousers with a relaxed fit. Perfect for creating effortlessly chic looks. Features elastic waistband for comfort.',
    rating: 4.9,
    reviews: 198,
    stock: 41,
    sku: 'KF-WP003'
  },

  // Women's Formal Pants
  {
    id: 'wf001',
    name: 'Tailored Dress Pants - Black',
    category: 'Formal',
    gender: 'Women',
    price: 5500,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    colors: ['Black', 'Navy', 'Charcoal'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Professional tailored dress pants with a perfect fit. Ideal for office wear and business meetings. Features flat front and side zip.',
    rating: 4.8,
    reviews: 143,
    stock: 36,
    sku: 'KF-WF001'
  },
  {
    id: 'wf002',
    name: 'Straight Leg Formal Pants - Gray',
    category: 'Formal',
    gender: 'Women',
    price: 5200,
    oldPrice: 6000,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    colors: ['Gray', 'Black', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Classic straight leg formal pants in premium fabric. Versatile and comfortable for all-day wear. Features belt loops and back pockets.',
    rating: 4.7,
    reviews: 128,
    stock: 44,
    sku: 'KF-WF002'
  },

  // Women's Traditional Wear
  {
    id: 'wt001',
    name: 'Embroidered Tulip Pants - Maroon',
    category: 'Traditional',
    gender: 'Women',
    price: 3800,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    colors: ['Maroon', 'Navy', 'Black', 'Emerald'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Beautiful embroidered tulip pants perfect for traditional outfits. Features intricate embroidery at the hem. Comfortable elastic waist.',
    rating: 4.9,
    reviews: 176,
    stock: 39,
    sku: 'KF-WT001'
  },
  {
    id: 'wt002',
    name: 'Silk Shalwar - Cream',
    category: 'Traditional',
    gender: 'Women',
    price: 4200,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    colors: ['Cream', 'White', 'Peach', 'Mint'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Luxurious silk shalwar with a comfortable fit. Perfect for pairing with traditional kurtas and kameez. Soft and elegant.',
    rating: 4.8,
    reviews: 134,
    stock: 47,
    sku: 'KF-WT002'
  },
  {
    id: 'wt003',
    name: 'Printed Palazzo Shalwar - Navy',
    category: 'Traditional',
    gender: 'Women',
    price: 3500,
    oldPrice: 4200,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    colors: ['Navy', 'Maroon', 'Teal'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Stylish printed palazzo shalwar with traditional motifs. Comfortable and fashionable for casual traditional wear. Breathable fabric.',
    rating: 4.6,
    reviews: 145,
    stock: 53,
    sku: 'KF-WT003'
  },

  // Unstitched Fabric - Men
  {
    id: 'um001',
    name: 'Premium Khaddar Fabric - Charcoal',
    category: 'Unstitched',
    gender: 'Men',
    price: 2800,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    colors: ['Charcoal', 'Navy', 'Black', 'Olive'],
    sizes: ['3.5m', '4m', '4.5m'],
    description: 'High-quality khaddar fabric perfect for winter wear. Soft texture with excellent warmth. Ideal for shalwar kameez and kurtas.',
    rating: 4.7,
    reviews: 89,
    stock: 72,
    sku: 'KF-UM001'
  },
  {
    id: 'um002',
    name: 'Lawn Cotton Fabric - White',
    category: 'Unstitched',
    gender: 'Men',
    price: 2200,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    colors: ['White', 'Cream', 'Sky Blue', 'Mint'],
    sizes: ['3.5m', '4m', '4.5m'],
    description: 'Premium lawn cotton fabric perfect for summer. Breathable and comfortable. Ideal for casual and formal shalwar kameez.',
    rating: 4.8,
    reviews: 167,
    stock: 85,
    sku: 'KF-UM002'
  },
  {
    id: 'um003',
    name: 'Wash & Wear Fabric - Navy',
    category: 'Unstitched',
    gender: 'Men',
    price: 2500,
    oldPrice: 3000,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    colors: ['Navy', 'Black', 'Gray', 'Brown'],
    sizes: ['3.5m', '4m', '4.5m'],
    description: 'Easy-care wash and wear fabric that requires minimal ironing. Perfect for busy professionals. Durable and long-lasting.',
    rating: 4.6,
    reviews: 134,
    stock: 68,
    sku: 'KF-UM003'
  },

  // Unstitched Fabric - Women
  {
    id: 'uw001',
    name: 'Embroidered Lawn 3-Piece - Pink',
    category: 'Unstitched',
    gender: 'Women',
    price: 5500,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    colors: ['Pink', 'Peach', 'Mint', 'Lavender'],
    sizes: ['3-Piece Set'],
    description: 'Beautiful embroidered lawn 3-piece suit with intricate threadwork. Includes shirt, dupatta, and trouser fabric. Perfect for summer.',
    rating: 4.9,
    reviews: 234,
    stock: 42,
    sku: 'KF-UW001'
  },
  {
    id: 'uw002',
    name: 'Printed Khaddar 3-Piece - Maroon',
    category: 'Unstitched',
    gender: 'Women',
    price: 4800,
    oldPrice: 5500,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    colors: ['Maroon', 'Navy', 'Emerald', 'Black'],
    sizes: ['3-Piece Set'],
    description: 'Elegant printed khaddar 3-piece with traditional motifs. Warm and comfortable for winter. Includes embroidered neckline.',
    rating: 4.8,
    reviews: 198,
    stock: 38,
    sku: 'KF-UW002'
  },
  {
    id: 'uw003',
    name: 'Chiffon Formal 3-Piece - Black',
    category: 'Unstitched',
    gender: 'Women',
    price: 7500,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    colors: ['Black', 'Navy', 'Burgundy', 'Emerald'],
    sizes: ['3-Piece Set'],
    description: 'Luxurious chiffon 3-piece with heavy embroidery and embellishments. Perfect for formal events and weddings. Includes silk trouser.',
    rating: 4.9,
    reviews: 156,
    stock: 24,
    sku: 'KF-UW003'
  },
  {
    id: 'uw004',
    name: 'Cotton Printed 2-Piece - Blue',
    category: 'Unstitched',
    gender: 'Women',
    price: 3200,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800',
    colors: ['Blue', 'Pink', 'Yellow', 'Green'],
    sizes: ['2-Piece Set'],
    description: 'Comfortable cotton printed 2-piece for everyday wear. Includes shirt and trouser fabric. Easy to stitch and maintain.',
    rating: 4.7,
    reviews: 178,
    stock: 61,
    sku: 'KF-UW004'
  },

  // Festive Wear - Men
  {
    id: 'mfw001',
    name: 'Velvet Sherwani Fabric - Maroon',
    category: 'Festive',
    gender: 'Men',
    price: 12500,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1622519407650-3df9883f76e5?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    colors: ['Maroon', 'Navy', 'Black', 'Emerald'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Luxurious velvet sherwani fabric with intricate embroidery. Perfect for weddings and special occasions. Includes matching pajama fabric.',
    rating: 4.9,
    reviews: 87,
    stock: 18,
    sku: 'KF-MFW001'
  },
  {
    id: 'mfw002',
    name: 'Embroidered Kurta Set - Gold',
    category: 'Festive',
    gender: 'Men',
    price: 9500,
    oldPrice: 11000,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1622519407650-3df9883f76e5?w=800',
    colors: ['Gold', 'Cream', 'White'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Elegant embroidered kurta set perfect for Eid and festive celebrations. Features golden threadwork and premium fabric.',
    rating: 4.8,
    reviews: 145,
    stock: 26,
    sku: 'KF-MFW002'
  },

  // Festive Wear - Women
  {
    id: 'wfw001',
    name: 'Bridal Lehenga Fabric - Red',
    category: 'Festive',
    gender: 'Women',
    price: 18500,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    colors: ['Red', 'Maroon', 'Pink', 'Gold'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Stunning bridal lehenga fabric with heavy embroidery and embellishments. Perfect for weddings. Includes blouse and dupatta fabric.',
    rating: 5.0,
    reviews: 67,
    stock: 12,
    sku: 'KF-WFW001'
  },
  {
    id: 'wfw002',
    name: 'Formal Party Wear 3-Piece - Navy',
    category: 'Festive',
    gender: 'Women',
    price: 9800,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    colors: ['Navy', 'Black', 'Emerald', 'Burgundy'],
    sizes: ['3-Piece Set'],
    description: 'Elegant formal party wear with sequin work and embroidery. Perfect for evening events and celebrations. Premium quality fabric.',
    rating: 4.9,
    reviews: 123,
    stock: 21,
    sku: 'KF-WFW002'
  },
  {
    id: 'wfw003',
    name: 'Embellished Maxi Dress - Peach',
    category: 'Festive',
    gender: 'Women',
    price: 8500,
    oldPrice: 10000,
    sale: true,
    badge: 'Sale',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    colors: ['Peach', 'Mint', 'Lavender', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Beautiful embellished maxi dress perfect for formal gatherings. Features delicate embroidery and flowing silhouette.',
    rating: 4.8,
    reviews: 167,
    stock: 29,
    sku: 'KF-WFW003'
  },

  // Additional Bestsellers
  {
    id: 'mp005',
    name: 'Stretch Chinos - Khaki',
    category: 'Casual',
    gender: 'Men',
    price: 4200,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    colors: ['Khaki', 'Navy', 'Black', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    description: 'Comfortable stretch chinos with modern fit. Perfect for casual office wear. Features stretch fabric for all-day comfort.',
    rating: 4.7,
    reviews: 201,
    stock: 58,
    sku: 'KF-MP005'
  },
  {
    id: 'wp004',
    name: 'Ankle Length Pants - Black',
    category: 'Casual',
    gender: 'Women',
    price: 3900,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    colors: ['Black', 'Navy', 'White', 'Beige'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Trendy ankle length pants with a modern cut. Versatile piece for creating stylish looks. Features side pockets and elastic waist.',
    rating: 4.8,
    reviews: 189,
    stock: 64,
    sku: 'KF-WP004'
  },
  {
    id: 'mf004',
    name: 'Pleated Dress Pants - Gray',
    category: 'Formal',
    gender: 'Men',
    price: 5900,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594938291221-94f18cbb5660?w=800',
    colors: ['Gray', 'Navy', 'Black'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Classic pleated dress pants with traditional styling. Perfect for formal business settings. Features quality construction.',
    rating: 4.6,
    reviews: 98,
    stock: 37,
    sku: 'KF-MF004'
  },
  {
    id: 'wf003',
    name: 'Cropped Formal Pants - Navy',
    category: 'Formal',
    gender: 'Women',
    price: 4800,
    oldPrice: null,
    sale: false,
    badge: 'New',
    isNew: true,
    image: 'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
    colors: ['Navy', 'Black', 'Gray', 'Burgundy'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Modern cropped formal pants perfect for contemporary office wear. Features clean lines and tailored fit.',
    rating: 4.7,
    reviews: 112,
    stock: 43,
    sku: 'KF-WF003'
  },
  {
    id: 'mt004',
    name: 'Waistcoat Shalwar Set - Black',
    category: 'Traditional',
    gender: 'Men',
    price: 7200,
    oldPrice: null,
    sale: false,
    badge: 'Premium',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1622519407650-3df9883f76e5?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    colors: ['Black', 'Navy', 'Maroon'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    description: 'Stylish waistcoat shalwar set perfect for semi-formal occasions. Features embroidered waistcoat and matching shalwar.',
    rating: 4.8,
    reviews: 134,
    stock: 31,
    sku: 'KF-MT004'
  },
  {
    id: 'wt004',
    name: 'Cigarette Shalwar - White',
    category: 'Traditional',
    gender: 'Women',
    price: 2800,
    oldPrice: null,
    sale: false,
    badge: 'Bestseller',
    isNew: false,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800',
    hoverImage: 'https://images.unsplash.com/photo-1610652492500-ded49c4e6d1e?w=800',
    colors: ['White', 'Black', 'Cream', 'Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Modern cigarette shalwar with slim fit. Perfect for pairing with short kurtas and kurtis. Comfortable elastic waist.',
    rating: 4.7,
    reviews: 223,
    stock: 71,
    sku: 'KF-WT004'
  }
];

// Initialize products in localStorage if not exists
if (!localStorage.getItem('kf_products')) {
  localStorage.setItem('kf_products', JSON.stringify(PRODUCTS));
}